### ISSUE TITLE
big bug, 

### ISSUE THREAD

**Issue by newyorkthink** [lucasmz1/Virt_Manager_AppImage#1]
```
Unable to connect to libvirt qemu:///system.

Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory

Libvirt URI is: qemu:///system

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 923, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 171, in open
    conn = libvirt.openAuth(self._open_uri,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_VirtuaFDdvm5/.junest/usr/lib/python3.11/site-packages/libvirt.py", line 147, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory
```

![image](https://github.com/lucasmz1/Virt_Manager_AppImage/assets/87791643/7226651f-22a8-423e-9b62-53c3bda0254c)

**Comment by lucasmz1** [comment]
@newyorkthink Have you tried the version 0.2? you must delete and create another connection. this is purely for testing porpoise only, so please don't expect much!
sorry about that!

**Comment by newyorkthink** [comment]
> @newyorkthink Have you tried the version 0.2? you must delete and create another connection. this is purely for testing porpoise only, so please don't expect much! sorry about that!

yes ,i use 0.2, and i not't other connect

**Comment by lucasmz1** [comment]
well, I've used junest as base for this build, I don't know what to do else!
